#  To create environment, execute:
#     conda env create -f conda-dev-env.yml
#
#  To activate:
#     conda activate mlir-dev
#
name: mlir-dev
channels:
  - conda-forge

dependencies:
  - gxx_linux-64   12.*
  - gcc_linux-64   12.*
  - ccache
  - sysroot_linux-64 >=2.14
  - cmake
  - ninja
  - python      ==3.11
  - level-zero-devel
  - git
  - llvm-openmp
